employename=input("enter employe name")
employeid=input("enter employe id")
employesalary=float input("enter the salary")
print("\n--employee details")
print("name:{employename}")
print("id:{employeid}")
print("salary:{employesalary}")
exp= int (input("enter the experience in years:"))

print(f"{name}, {emp_id}, {age}, {salary}")
print(f"\n\n{exp}")